name: Deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'  # Make sure this matches your .NET version

    - name: Restore dependencies
      run: dotnet restore learningapp.sln  # Adjust if you are targeting a specific project file instead

    - name: Build the solution
      run: dotnet build learningapp.sln --configuration Release --no-restore

    - name: Publish the app
      run: dotnet publish learningapp.sln --configuration Release --output ./myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: '<your-azure-webapp-name>'  # Replace with your Azure Web App name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Ensure you set this secret in GitHub
        package: ./myapp
